feat(coreos-install): Add option to install a cloud-config file.

diff --git a/bin/coreos-install b/bin/coreos-install
--- a/bin/coreos-install
+++ b/bin/coreos-install
@@ -31,6 +31,7 @@ Options:
     -d DEVICE   Install CoreOS to the given device.
     -V VERSION  Version to install (e.g. alpha) [default: ${VERSION_ID}]
     -o OEM      OEM type to install (e.g. ami) [default: ${OEM_ID:-(none)}]
+    -c CLOUD    Insert a cloud-init config to be executed on boot.
     -t TMPDIR   Temporary location with enough space to download images.
     -v          Super verbose, for debugging.
     -h          This ;-)
@@ -119,13 +120,15 @@ BeiJ6tEeDHDzdA==
 "
 
 DEVICE=""
+CLOUDINIT=""
 
-while getopts "V:d:o:t:vh" OPTION
+while getopts "V:d:o:c:t:vh" OPTION
 do
     case $OPTION in
         V) VERSION_ID="$OPTARG" ;;
         d) DEVICE="$OPTARG" ;;
         o) OEM_ID="$OPTARG" ;;
+        c) CLOUDINIT="$OPTARG" ;;
         t) export TMPDIR="$OPTARG" ;;
         v) set -x ;;
         h) echo "$USAGE"; exit;;
@@ -146,6 +149,11 @@ fi
 
 if [[ ! -w "${DEVICE}" ]]; then
     echo "$0: Target block device (${DEVICE}) is not writable (are you root?)" >&2
+    exit 1
+fi
+
+if [[ -n "${CLOUDINIT}" && ! -f "${CLOUDINIT}" ]]; then
+    echo "$0: Cloud config file (${CLOUDINIT}) does not exist." >&2
     exit 1
 fi
 
@@ -204,6 +212,28 @@ bunzip2 -v --stdout "${WORKDIR}/${IMAGE_NAME}" >"${DEVICE}"
 
 # inform the OS of partition table changes
 partprobe "${DEVICE}"
+
+if [[ -n "${CLOUDINIT}" ]]; then
+    # The ROOT partition should be #9 but make no assumptions here!
+    # Also don't mount by label directly in case other devices conflict.
+    ROOT_DEV=$(lsblk -rp -o name,partlabel "${DEVICE}"  | \
+               awk '$2 == "ROOT" {print $1; exit}')
+
+    if [[ -z "${ROOT_DEV}" ]]; then
+        echo "Unable to find new ROOT partition on ${DEVICE}" >&2
+        exit 1
+    fi
+
+    echo "Installing cloud-config..."
+    mkdir -p "${WORKDIR}/rootfs"
+    mount -t btrfs -o subvol=root "${ROOT_DEV}" "${WORKDIR}/rootfs"
+    trap "umount '${WORKDIR}/rootfs' && rm -rf '${WORKDIR}'" EXIT
+
+    mkdir -p "${WORKDIR}/rootfs/var/lib/coreos-install"
+    cp "${CLOUDINIT}" "${WORKDIR}/rootfs/var/lib/coreos-install/user_data"
+
+    umount "${WORKDIR}/rootfs"
+fi
 
 rm -rf "${WORKDIR}"
 trap - EXIT
