coreos-install: add support for Ignition

diff --git a/bin/coreos-install b/bin/coreos-install
--- a/bin/coreos-install
+++ b/bin/coreos-install
@@ -35,6 +35,7 @@ Options:
     -C CHANNEL  Release channel to use (e.g. beta) [default: ${CHANNEL_ID}]
     -o OEM      OEM type to install (e.g. ami) [default: ${OEM_ID:-(none)}]
     -c CLOUD    Insert a cloud-init config to be executed on boot.
+    -i IGNITION Insert an Ignition config to be executed on boot.
     -t TMPDIR   Temporary location with enough space to download images.
     -v          Super verbose, for debugging.
     -b BASEURL  URL to the image mirror
@@ -194,7 +195,7 @@ X8FjXVJ/8MWi91Z0pHcLzhYZYn2IACvaaUh06HyyAIiDlgWRC7zgMQ==
 DEVICE=""
 CLOUDINIT=""
 
-while getopts "V:C:d:o:c:t:b:nvh" OPTION
+while getopts "V:C:d:o:c:i:t:b:nvh" OPTION
 do
     case $OPTION in
         V) VERSION_ID="$OPTARG" ;;
@@ -202,6 +203,7 @@ do
         d) DEVICE="$OPTARG" ;;
         o) OEM_ID="$OPTARG" ;;
         c) CLOUDINIT="$OPTARG" ;;
+        i) IGNITION="$OPTARG" ;;
         t) export TMPDIR="$OPTARG" ;;
         v) set -x ;;
         b) BASE_URL="$OPTARG" ;;
@@ -240,6 +242,13 @@ if [[ -n "${CLOUDINIT}" ]]; then
         fi
     else
         echo "$0: coreos-cloudinit not found. Could not validate config. Continuing..." >&2
+    fi
+fi
+
+if [[ -n "${IGNITION}" ]]; then
+    if [[ ! -f "${IGNITION}" ]]; then
+        echo "$0: Ignition config file (${IGNITION}) does not exist." >&2
+        exit 1
     fi
 fi
 
@@ -332,6 +341,29 @@ if [[ -n "${CLOUDINIT}" ]] || [[ -n "${COPY_NET}" ]]; then
     fi
 
     umount "${WORKDIR}/rootfs"
+    trap "rm -rf '${WORKDIR}'" EXIT
+fi
+
+if [[ -n "${IGNITION}" ]]; then
+    # The OEM partition should be #3 but make no assumptions here!
+    # Also don't mount by label directly in case other devices conflict.
+    OEM_DEV=$(blkid -t "LABEL=OEM" -o device "${DEVICE}"*)
+
+    if [[ -z "${OEM_DEV}" ]]; then
+      echo "Unable to find new OEM partition on ${DEVICE}" >&2
+      exit 1
+    fi
+
+    mkdir -p "${WORKDIR}/oemfs"
+    mount "${OEM_DEV}" "${WORKDIR}/oemfs"
+    trap "umount '${WORKDIR}/oemfs' && rm -rf '${WORKDIR}'" EXIT
+
+    echo "Installing Ignition config ${IGNITION}..."
+    cp "${IGNITION}" "${WORKDIR}/oemfs/coreos-install.json"
+    echo  "set linux_append=\"coreos.config.url=oem:///coreos-install.json"\" > "${WORKDIR}/oemfs/grub.cfg"
+
+    umount "${WORKDIR}/oemfs"
+    trap "rm -rf '${WORKDIR}'" EXIT
 fi
 
 rm -rf "${WORKDIR}"
