feat(coreos_startup): generate host ssh keys
if the stateful partition doesn't have ssh keys then generate them. We
don't need any fancy dependencies here for the sshd service because we
use socket activation for sshd.

diff --git a/coreos_startup b/coreos_startup
--- a/coreos_startup
+++ b/coreos_startup
@@ -18,6 +18,23 @@ remember_mount()
 {
     UNDO_MOUNTS="$1 ${UNDO_MOUNTS}"
 }
+setup_ssh()
+{
+  SSH_DIR=/mnt/stateful_partition/etc/ssh
+  mkdir -p ${SSH_DIR}
+
+  if ! sshd -t > /dev/null ; then
+    # sshd will not start with current config, generate a new set of keys.
+    for KEY_TYPE in rsa dsa ; do
+      KEY_FILE=${SSH_DIR}/ssh_host_${KEY_TYPE}_key
+      # If keys exist delete them because they are not valid and ssh-keygen
+      # will not overwrite them.
+      rm -f ${KEY_FILE} ${KEY_FILE}.pub
+      ssh-keygen -q -f ${KEY_FILE} -N '' -t ${KEY_TYPE} ||
+        echo "Failed to generate ssh key."
+    done
+  fi
+}
 mount_or_fail()
 {
   local mount_point
@@ -63,6 +80,7 @@ if [ $(date +%Y) -lt 1970 ]; then
 fi
 
 mount_stateful
+setup_ssh
 
 # Make sure unencrypted stateful partition has the needed directories.
 for d in home home/core home/core/user home/root home/user; do
