feat(coreos_startup): auto-grow stateful partition
If the disk has unused space at the end of the disk the state partition
will be expanded during boot to use all available space.

diff --git a/coreos_startup b/coreos_startup
--- a/coreos_startup
+++ b/coreos_startup
@@ -64,6 +64,9 @@ mount_stateful()
   # initrd+tftpboot (used for ARM factory images), ROOTDEV_TYPE will be
   # /dev/ram.
   if [ "$ROOTDEV_RET_CODE" = "0" -a "$ROOTDEV_TYPE" != "/dev/ram" ]; then
+    #XXX: by-label links aren't working at this point during boot
+    #resize_stateful "/dev/disk/by-label/STATE"
+    resize_stateful "${ROOTDEV_TYPE}9"
     if ! mount -L STATE -n -t ext4 -o commit=600 /mnt/stateful_partition; then
       echo "ERROR: could not mount $STATE_DEV"
     fi
@@ -73,6 +76,56 @@ mount_stateful()
   # as we may not have an OEM filesystem in all cases.
   mount -L OEM -n -t ext4 -o nodev,noexec,nosuid,commit=600,ro \
     /usr/share/oem
+}
+resize_stateful()
+{
+    if [ ! -b "$1" ]; then
+        echo "$1 is not a block device" >&2
+        return 1
+    fi
+
+    STATE_DEV="`readlink -f "$1"`"
+    STATE_PART="${STATE_DEV##*[^0-9]}"
+    DISK_DEV="${STATE_DEV%[0-9]*}"
+
+    if sgdisk -v "$DISK_DEV" | grep -q "^Problem: The secondary header"; then
+        echo "Extending STATE partition..." >&2
+
+        # No resize operation so copy unknown partition properties.
+        info="`sgdisk --info=$STATE_PART "$DISK_DEV"`"
+        guid="`echo "$info" | mawk '/^Partition unique GUID:/{print $4}'`"
+        start="`echo "$info" | mawk '/^First sector:/{print $3}'`"
+        if [ -z "$guid" -o -z "$start" ]; then
+            echo "Resize failed: unable to parse sgdisk output" >&2
+            return 1
+        fi
+
+        # No turning back now!
+        if ! sgdisk --move-second-header \
+                --delete=$STATE_PART \
+                --new=$STATE_PART:$start:0 \
+                --partition-guid=$STATE_PART:$guid \
+                --typecode=$STATE_PART:0x0700 \
+                --change-name=$STATE_PART:STATE \
+                "$DISK_DEV"; then
+            echo "Resize failed: error updating GPT" >&2
+            return 1
+        fi
+
+        # sgdisk only can trigger a full-disk reload which fails while the
+        # root filesystem is mounted. partprobe from parted is fancier.
+        partprobe "$DISK_DEV"
+
+        e2fsck -p -f "$STATE_DEV"
+        if [ "$?" != 0 -a "$?" != 1 ]; then
+            echo "Resize failed: error during fsck" >&2
+            return 1
+        fi
+        if ! resize2fs "$STATE_DEV"; then
+            echo "Resize failed: error during resize2fs" >&2
+            return 1
+        fi
+    fi
 }
 
 
